# -*- mode: ruby -*-
# vi: set ft=ruby :


# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  # config.vm.box_url = "http://domain.com/path/to/above.box"

  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.hostname = "your.post.my.sms"

  # folder bindings
  config.vm.synced_folder "..", "/etc/puppet/modules/post2sms"

  config.vm.provision :shell, inline: "apt-get update"
  config.vm.provision :puppet do |puppet|
    puppet.module_path = "modules"
  end

end
